
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const FETCH_All_CATEGORIES = 'FETCH_All_CATEGORIES';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_CART ='FETCH_CART';
export const ADD_ITEM_TO_CART ='ADD_ITEM_TO_CART';
export const FETCH_CART_PRODUCTLIST='FETCH_CART_PRODUCTLIST';
